# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weblink', models.URLField(help_text='Enter Link to detail page for the item', max_length=600, verbose_name='Web Address')),
                ('unit', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('1', 'saved'), ('2', 'requested'), ('3', 'denied'), ('4', 'approved')], default='1', max_length=1)),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter Manufacturer's Name", max_length=60, verbose_name='Manufacturer Name')),
                ('part_number', models.CharField(help_text='Enter Part Number', max_length=60, verbose_name='Part Number')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter Vendors's Name", max_length=60, verbose_name='Vendor Name')),
                ('part_number', models.CharField(help_text='Enter Part Number', max_length=60, verbose_name='Part Number')),
            ],
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemrequest.Manufacturer'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemrequest.Vendor'),
        ),
    ]
