# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='requested_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='description',
            field=models.TextField(help_text='Full description of the item'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='weblink',
            field=models.URLField(blank=True, help_text='Enter Link to detail page for the item', max_length=600, null=True, verbose_name='Web Address'),
        ),
    ]
