# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemrequest', '0002_auto_20170122_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='requested_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='vendor',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='manufacturer_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='requester',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='weblink',
            field=models.URLField(blank=True, default=1, help_text='Enter Link to detail page for the item', max_length=600, verbose_name='Web Address'),
            preserve_default=False,
        ),
    ]
