# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemrequest', '0004_auto_20170122_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemrequest.Uom'),
        ),
    ]
