# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemrequest', '0005_auto_20170122_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='manufacturer_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manufacturer Part Number'),
        ),
    ]
